### ISSUE TITLE
the very first example in heiku tutorial is erroneous 

### ISSUE THREAD

**Issue by dorost1234** [deepmind/dm-haiku#320]
Hi
I am trying to run the very first example in Heiku tutorial:
```
import haiku as hk
import jax
import jax.numpy as jnp
import numpy as np


class MyLinear1(hk.Module):

  def __init__(self, output_size, name=None):
    super().__init__(name=name)
    self.output_size = output_size

  def __call__(self, x):
    j, k = x.shape[-1], self.output_size
    w_init = hk.initializers.TruncatedNormal(1. / np.sqrt(j))
    w = hk.get_parameter("w", shape=[j, k], dtype=x.dtype, init=w_init)
    b = hk.get_parameter("b", shape=[k], dtype=x.dtype, init=jnp.ones)
    return jnp.dot(x, w) + b

def _forward_fn_linear1(x):
  module = MyLinear1(output_size=2)
  return module(x)

forward_linear1 = hk.transform(_forward_fn_linear1)

print(forward_linear1)
```

getting these erorrs:
```
Traceback (most recent call last):
  File "code.py", line 1, in <module>
    import haiku as hk
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/haiku/__init__.py", line 23, in <module>
    from haiku import testing
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/haiku/testing.py", line 17, in <module>
    from haiku._src.test_utils import transform_and_run
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/haiku/_src/test_utils.py", line 24, in <module>
    from absl.testing import parameterized
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/absl/testing/parameterized.py", line 218, in <module>
    from absl.testing import absltest
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/absl/testing/absltest.py", line 57, in <module>
    from absl import app
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/site-packages/absl/app.py", line 35, in <module>
    import pdb
  File "/fsx/dara/conda/envs/heiku/lib/python3.8/pdb.py", line 77, in <module>
    import code
  File "/data/home/dara/codes/heiku/code.py", line 7, in <module>
    class MyLinear1(hk.Module):
AttributeError: partially initialized module 'haiku' has no attribute 'Module' (most likely due to a circular import)
```
versions I use:
```
dm-haiku                  0.0.7.dev0               pypi_0    pypi
jax                       0.3.1                    pypi_0    pypi
jaxlib                    0.3.0+cuda11.cudnn82          pypi_0    pypi
```

thanks for your help

**Comment by tomhennigan** [comment]
Hi @dorost1234 , I think the issue is that you have a file called `code.py` in your current directory and this is clashing with a builtin module called `code` that `pdb` depends on. You should be able to fix this by renaming `code.py` to `mycode.py`.
