### ISSUE TITLE
Passing a list of layers to an haiku Module

### ISSUE THREAD

**Issue by thomashirtz** [deepmind/dm-haiku#441]
I have an application where I would be able to change the structure of my two networks inside my `Config`, however when I am attempting to do so I am getting an error :

```
Traceback (most recent call last):
  File "/home/app/project/scripts/train_vae_cnn.py", line 1, in <module>
    import project.vae_cnn_mnist as vae
  File "/home/app/project/project/vae_cnn_mnist.py", line 22, in <module>
    class Config(hk.Module):
  File "/home/app/project/project/vae_cnn_mnist.py", line 34, in Config
    hk.Linear(400),
  File "/opt/conda/lib/python3.8/site-packages/haiku/_src/module.py", line 138, in __call__
    init(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/haiku/_src/module.py", line 404, in wrapped
    raise ValueError(
ValueError: All `hk.Module`s must be initialized inside an `hk.transform`.
```

This is the code:
```
from typing import Dict, Iterator, NamedTuple, Optional, Sequence, Tuple, List

import haiku as hk
import jax
import jax.numpy as jnp
import numpy as np
import optax

from project import utilities
from project.types import Batch, PRNGKey, Layer


def kaiming_he_linear(output_size: int) -> hk.Linear:
    # Returns linear layer with Kaiming He initialization
    # https://github.com/deepmind/dm-haiku/issues/6#issuecomment-589696286
    return hk.Linear(
        output_size=output_size,
        w_init=hk.initializers.VarianceScaling(scale=2.0),
    )


class Config(NamedTuple):
    # Training
    seed: int = 0
    learning_rate: float = 0.0005
    num_epochs: int = 100
    batch_size: int = 128

    # Network
    latent_size: int = 3
    sample_shape: Sequence[int] = [28, 28]

    encoder_layer_list: Sequence[Layer] =[
        hk.Linear(400),
        jax.nn.relu,
        hk.Linear(100),
        jax.nn.relu,
    ]

    decoder_layer_list: Sequence[Layer] = [
        hk.Linear(100),
        jax.nn.relu,
        hk.Linear(400),
        jax.nn.relu,
    ]


class Encoder(hk.Module):
    """Encoder model."""

    def __init__(
        self,
        latent_size: int,
        layer_list: List[Layer],
    ):
        super().__init__()
        self._latent_size = latent_size
        self._layer_list = layer_list

    def __call__(self, x: jnp.ndarray) -> Tuple[jnp.ndarray, jnp.ndarray]:
        x = hk.Flatten()(x)
        x = hk.Sequential(self._layer_list)(x)
        mu = kaiming_he_linear(self._latent_size)(x)
        log_sigma = kaiming_he_linear(self._latent_size)(x)
        return mu, log_sigma
...
```
Is it not possible to do something like that ?

**Comment by LenaMartens** [comment]
Hi Thomas!

You can get around this by writing those layers as functions, delaying their initialization. eg. using lambdas:
```
encoder_layer_list: Sequence[Layer] =[
        lambda x: hk.Linear(400)(x),
        jax.nn.relu,
        lambda x: hk.Linear(100)(x),
        jax.nn.relu,
   ]
```
or, because you're calling a `Sequential` on it later, express it as a Sequential in your Config:
```
encoder_layer_sequence: hk.Sequential = lambda x: hk.Sequential([
        hk.Linear(400),
        jax.nn.relu,
        hk.Linear(100),
        jax.nn.relu,
   ])(x)
```

**Comment by thomashirtz** [comment]
Thank you for your answer ! I'll do that :)
