### ISSUE TITLE
How to use ConvLSTM?

### ISSUE THREAD

**Issue by alembcke** [deepmind/dm-haiku#584]
I built a CNN that works OK on my dataset, as well as a CNN-to-RNN that has slightly better performance.  I want to try out ConvLSTM, but keep getting an error.

Here is a pared-down example of what I am trying to do:

```py
import jax
import haiku as hk

# create random dataset
key = jax.random.PRNGKey(0)
train_x = jax.random.normal(key, (10, 10, 11, 10, 10))

def conv_lstm(x):
    """Defines a vanilla Convolutional LSTM network."""
    batch_size, time_steps, feature_dim1, feature_dim2, feature_dim3 = x.shape

    core = hk.DeepRNN([
        hk.Conv2DLSTM(
            input_shape=[feature_dim1, feature_dim2, feature_dim3],
            output_channels=64,
            kernel_shape=[1, 1]),
        jax.nn.relu
        ])

    x, state = hk.dynamic_unroll(core, x, core.initial_state(time_steps))

    return x

network = hk.transform_with_state(conv_lstm)

rng_key = jax.random.PRNGKey(1)
params, state = network.init(rng_key, train_x[:0, :, :, :, :])
```

The error I keep getting is:
```
Traceback (most recent call last):
  File "/home/alexlembcke/conv_lstm/conv_lstm_test.py", line 26, in <module>
    params, state = network.init(rng_key, train_x[:0, :, :, :, :])
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/transform.py", line 338, in init_fn
    f(*args, **kwargs)
  File "/home/alexlembcke/conv_lstm/conv_lstm_test.py", line 19, in conv_lstm
    x, state = hk.dynamic_unroll(core, x, core.initial_state(time_steps))
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/recurrent.py", line 199, in dynamic_unroll
    scan_result = scan(
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/stateful.py", line 600, in scan
    _, y0 = f(init, x0)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/recurrent.py", line 190, in scan_f
    outputs, next_state = core(inputs, prev_state)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/recurrent.py", line 750, in __call__
    current_inputs, next_state = layer(current_inputs, state[state_idx])
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/recurrent.py", line 417, in __call__
    gates = input_to_hidden(inputs) + hidden_to_hidden(state.hidden)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/alexlembcke/.local/lib/python3.10/site-packages/haiku/_src/conv.py", line 176, in __call__
    raise ValueError(f"Input to ConvND needs to have rank in {allowed_ranks},"
ValueError: Input to ConvND needs to have rank in [3, 4], but input has shape (10, 11, 10, 10, 64).
```

Any ideas on how to get this to work, or any examples I can look at to get a better idea of how to use ConvLSTMs?

**Comment by simonkamronn-inc** [comment]
Don't include your channel dimension (last one) in the input_shape. 

```
import jax
import haiku as hk

# create random dataset
key = jax.random.PRNGKey(0)
train_x = jax.random.normal(key, (10, 10, 11, 10, 10))


def conv_lstm(x):
    """Defines a vanilla Convolutional LSTM network."""
    batch_size, time_steps, feature_dim1, feature_dim2, feature_dim3 = x.shape

    core = hk.DeepRNN(
        [
            hk.Conv2DLSTM(
                input_shape=[feature_dim1, feature_dim2],
                output_channels=64,
                kernel_shape=[1, 1],
            ),
            jax.nn.relu,
        ]
    )

    x, state = hk.dynamic_unroll(core, x, core.initial_state(time_steps))

    return x


network = hk.transform_with_state(conv_lstm)

rng_key = jax.random.PRNGKey(1)
params, state = network.init(rng_key, train_x[:0, :, :, :, :])

out, state = network.apply(params, state, rng_key, train_x)
assert out.shape == (10, 10, 11, 10, 64)
```

**Comment by alembcke** [comment]
That worked, thank you!
