### ISSUE TITLE
Haiku leaks tracers when used with JIT and custom JVP

### ISSUE THREAD

**Issue by NeilGirdhar** [deepmind/dm-haiku#99]
Am I using Haiku incorrectly?

When I enable `export JAX_CHECK_TRACER_LEAKS=1` and then
```python
import haiku as hk
import jax

@jax.custom_jvp
def t(y):
    return y

def t_jvp(primals, tangents):
    assert False

t.defjvp(t_jvp)

@jax.jit
def s(y):
    return t(y)

def f():
    return s(0.0)

transformed = hk.transform_with_state(f)
transformed.init(None)
```
gives
```
Traceback (most recent call last):
  File "/home/neil/src/cmm/a.py", line 26, in <module>
    transformed.init(None)
  File "/home/neil/src/dm-haiku/haiku/_src/transform.py", line 281, in init_fn
    f(*args, **kwargs)
  File "/home/neil/src/cmm/a.py", line 22, in f
    return s(0.0)
  File "/home/neil/.pyenv/versions/3.9.1/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
jax._src.traceback_util.FilteredStackTrace: Exception: Leaked trace MainTrace(0,DynamicJaxprTrace)

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.
```

**Comment by NeilGirdhar** [comment]
Seems to be a JAX problem actually.

**Comment by tomhennigan** [comment]
Thanks for digging into this!
